export const DUMMY_NOTIFICATIONS = [
  {
    id: "1",
    message: "Nuevo mensaje de Juan. Por favor, revisa tu buzón de entrada.",
    isUnread: true,
    showButtons: true,
  },
  {
    id: "2",
    message: "Recordatorio de reunión a las 3 PM. No olvides preparar los documentos.",
    isUnread: false,
    showButtons: false,
  },
  {
    id: "3",
    message: "Tu suscripción a nuestro servicio ha sido renovada exitosamente.",
    isUnread: true,
    showButtons: false,
  },
  {
    id: "4",
    message: "Alerta de seguridad: Se ha detectado un intento de inicio de sesión sospechoso.",
    isUnread: true,
    showButtons: true,
  },
  {
    id: "5",
    message: "Felicitaciones, tu comentario ha recibido más de 100 likes.",
    isUnread: false,
    showButtons: false,
  },
  {
    id: "6",
    message: "Recordatorio: Tienes una cita con el dentista mañana a las 10 AM.",
    isUnread: true,
    showButtons: false,
  },
  {
    id: "7",
    message: "Promoción especial: Obtén un 20% de descuento en tu próxima compra.",
    isUnread: false,
    showButtons: true,
  },
  {
    id: "8",
    message: "Encuesta de satisfacción: Nos encantaría conocer tu opinión sobre nuestro servicio.",
    isUnread: false,
    showButtons: true,
  },
  {
    id: "9",
    message: "Actualización disponible: Nueva versión de la app ya está disponible en la tienda.",
    isUnread: true,
    showButtons: false,
  },
  {
    id: "10",
    message: "La actualización del sistema está completa. Reinicia tu dispositivo.",
    isUnread: true,
    showButtons: false,
  },
  {
    id: "11",
    message: "Nuevo mensaje de Juan. Por favor, revisa tu buzón de entrada.",
    isUnread: true,
    showButtons: true,
  },
  {
    id: "12",
    message: "Recordatorio de reunión a las 3 PM. No olvides preparar los documentos.",
    isUnread: false,
    showButtons: false,
  },
  {
    id: "13",
    message: "Tu suscripción a nuestro servicio ha sido renovada exitosamente.",
    isUnread: true,
    showButtons: false,
  },
  {
    id: "14",
    message: "Alerta de seguridad: Se ha detectado un intento de inicio de sesión sospechoso.",
    isUnread: true,
    showButtons: true,
  },
  {
    id: "15",
    message: "Felicitaciones, tu comentario ha recibido más de 100 likes.",
    isUnread: false,
    showButtons: false,
  },
  {
    id: "16",
    message: "Recordatorio: Tienes una cita con el dentista mañana a las 10 AM.",
    isUnread: true,
    showButtons: false,
  },
  {
    id: "17",
    message: "Promoción especial: Obtén un 20% de descuento en tu próxima compra.",
    isUnread: false,
    showButtons: true,
  },
  {
    id: "18",
    message: "Encuesta de satisfacción: Nos encantaría conocer tu opinión sobre nuestro servicio.",
    isUnread: false,
    showButtons: true,
  },
  {
    id: "19",
    message: "Actualización disponible: Nueva versión de la app ya está disponible en la tienda.",
    isUnread: true,
    showButtons: false,
  },
  {
    id: "20",
    message: "La actualización del sistema está completa. Reinicia tu dispositivo.",
    isUnread: true,
    showButtons: false,
  },
];
